config/routes.rb
Myapp::Application.routes.draw do

  match '/users' => 'home#index'
  match '/users/password' => 'home#index'
  match '/users/password/new' => 'home#index'
  match '/users/sign_up' => 'home#index'
  devise_for :users

  match 'home' => 'home#index'
  match '/attendances/search' => 'attendances#search', :as => :attendances_search
  match '/attendances/:year/:month/edit' => 'attendances#edit'
  match '/attendances/update' => 'attendances#update', :as => :attendances_update
  
  match '/withdraws/search' => 'withdraws#search', :as => :withdraws_search
  match '/withdraws/:year/:month/edit' => 'withdraws#edit'
  match '/withdraws/update' => 'withdraws#update', :as => :withdraws_update

  match '/salaries/search' => 'salaries#search', :as => :salaries_search
  match '/salaries/:year/edit' => 'salaries#edit'
  match '/salaries/update' => 'salaries#update', :as => :salaries_update

  match '/summary' => 'summary#index', :as => :summary
  match '/summary/search' => 'summary#search', :as => :summary_search

  match '/employees/resign/:id' => 'employees#resign', :as => :employee_resign
  match '/employees/entry/:id' => 'employees#entry', :as => :employee_entry
  match '/employees/index_resign' => 'employees#index_resign', :as => :employee_index_resign

  resources :employees, :attendances, :salaries, :withdraws

  root :to => 'home#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :address, :birth_date, :fax, :id_card, \
      :join_date, :mobile, :name, :resign_date, :telephone, :status

  has_many :attendances
  has_many :withdraws
  has_many :salarys
  belongs_to :worktype

  DISABLE = 0
  ACTIVE = 1
  RESIGN = 2

  scope :active, where("status = #{ACTIVE}")
  scope :resign, where("status = #{RESIGN}")
  scope :all, where("status in (#{RESIGN},#{ACTIVE})").order("status")
  
  def resigned?
    return status == RESIGN 
  end
end

app/controllers/employees_controller.rb
 #encoding: UTF-8

class EmployeesController < ApplicationController

  def index
    @employees = Employee.active
  end

  def index_resign
    @employees = Employee.resign
  end

  def new
  	@employee = Employee.new
  end

	def create
    last = Employee.last
    id_card = last.nil? ? 100001 : last.id + 100001
    @employee = Employee.new(params[:employee])
    @employee.id_card = id_card
    @employee.join_date = Time.now
		if @employee.save
			redirect_to(@employee, :notice => "新建员工成功")
		else
			render :action => "new"
		end
	end

	def edit
		@employee = Employee.find(params[:id])
	end

	def show
		@employee = Employee.find(params[:id])
	end

	def update
		@employee = Employee.find(params[:id])
		if @employee.update_attributes(params[:employee])
			redirect_to(@employee, :notice => "员工信息更新成功.")
		else
			render :action => "edit"
		end
	end

	def destroy
	  @employee = Employee.find(params[:id])
    @employee.update_attributes(:status => Employee::DISABLE)
	  respond_to do |format|
	    format.html { redirect_to employees_url }
	    format.json { head :no_content }
	  end
	end

  def resign
    @employee = Employee.find(params[:id])
    @employee.update_attributes(:status => Employee::RESIGN, :resign_date => Time.now)
    redirect_to(employees_url, :notice => "员工离职成功.")
  end

  def entry
    @employee = Employee.find(params[:id])
    @employee.update_attributes(:status => Employee::ACTIVE, :join_date => Time.now)
    redirect_to(employee_index_resign_path, :notice => "员工重新入职成功.")
  end

private
  def set_nav
    @nav_employee = "active"
  end
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@employee.errors.count, "error") %> 保存失败:</h2>
    <ul>
    <% @employee.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :name, "姓名" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth_date, "生日" %><br />
    <%= f.text_field :birth_date %>
  </div>
  <div class="field">
    <%= f.label :mobile, "手机" %><br />
    <%= f.telephone_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :telephone, "座机" %><br />
    <%= f.telephone_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :fax, "传真" %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :address, "地址" %><br />
    <%= f.text_area :address, :rows => 3 %>
  </div>

  <div class="actions">
    <%= f.submit "保 存" %>
  </div>
<% end %>
<br/>

app/views/employees/edit.html.erb
<h3>编辑员工</h3>
 
<%= render 'form' %>

<%= link_to '查看', @employee %> |
<%= link_to '返回', employees_path %>

app/views/employees/index.html.erb
<ul class="nav nav-tabs nav-justified" role="tablist">
  <li class="active"><a href="#">员工列表</a></li>
  <li><a href="<%= employee_index_resign_path %>">离职员工列表</a></li>
</ul>

<table class="table table-striped">
  <tr>
    <th>工号</th>
    <th>姓名</th>
		<th>手机</th>
		<th>座机</th>
		<th>操作</th>
  </tr>
 
<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.id_card %></td>
    <td><%= employee.name %></td>
		<td><%= employee.mobile %></td>
		<td><%= employee.telephone %></td>
    <td><%= link_to '查看', employee %> |
    <%= link_to '编辑', edit_employee_path(employee) %> |
    <%= link_to '离职', employee_resign_path(employee), :confirm => '是否确认离职?' %></td>
  </tr>
<% end %>
</table>
 
<br />
 
<%= link_to '新建员工', new_employee_path %>

app/views/employees/index_resign.html.erb
<ul class="nav nav-tabs nav-justified" role="tablist">
  <li><a href="<%= employees_path %>">员工列表</a></li>
  <li class="active"><a href="#">离职员工列表</a></li>
</ul>

<table class="table table-striped">
  <tr>
    <th>工号</th>
    <th>姓名</th>
    <th>手机</th>
    <th>座机</th>
    <th>操作</th>
  </tr>
 
<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.id_card %></td>
    <td><%= employee.name %></td>
    <td><%= employee.mobile %></td>
    <td><%= employee.telephone %></td>
    <td><%= link_to '重新入职', employee_entry_path(employee), :confirm => '是否确认重新入职?' %> |
  <%= link_to '删除', employee, :confirm => '是否确认删除?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/employees/new.html.erb
<h3>新建员工</h3>
 
<%= render 'form' %>
 
<%= link_to '返回', employees_path %>

app/views/employees/show.html.erb
<h3>员工信息</h3>
 
<div class="field">
  <%= label_tag :id_card, "工号:" %> <%= @employee.id_card %>
</div> 
<div class="field">
  <%= label_tag :name, "姓名:" %> <%= @employee.name %>
</div>
<div class="field">
  <%= label_tag :birth_date, "生日:" %> <%= @employee.birth_date %>
</div>
<div class="field">
  <%= label_tag :mobile, "手机:" %> <%= @employee.mobile %>
</div>
<div class="field">
  <%= label_tag :telephone, "座机:" %> <%= @employee.telephone %>
</div>
<div class="field">
  <%= label_tag :fax, "传真:" %> <%= @employee.fax %>
</div>
<div class="field">
  <%= label_tag :address, "地址:" %> <%= @employee.address %>
</div>


<%= link_to '编辑', edit_employee_path(@employee) %> |
<%= link_to '返回', employees_path %>