config/routes.rb
Myapp::Application.routes.draw do

  match '/users' => 'home#index'
  match '/users/password' => 'home#index'
  match '/users/password/new' => 'home#index'
  match '/users/sign_up' => 'home#index'
  devise_for :users

  match 'home' => 'home#index'
  match '/attendances/search' => 'attendances#search', :as => :attendances_search
  match '/attendances/:year/:month/edit' => 'attendances#edit'
  match '/attendances/update' => 'attendances#update', :as => :attendances_update
  
  match '/withdraws/search' => 'withdraws#search', :as => :withdraws_search
  match '/withdraws/:year/:month/edit' => 'withdraws#edit'
  match '/withdraws/update' => 'withdraws#update', :as => :withdraws_update

  match '/salaries/search' => 'salaries#search', :as => :salaries_search
  match '/salaries/:year/edit' => 'salaries#edit'
  match '/salaries/update' => 'salaries#update', :as => :salaries_update

  match '/summary' => 'summary#index', :as => :summary
  match '/summary/search' => 'summary#search', :as => :summary_search

  match '/employees/resign/:id' => 'employees#resign', :as => :employee_resign
  match '/employees/entry/:id' => 'employees#entry', :as => :employee_entry
  match '/employees/index_resign' => 'employees#index_resign', :as => :employee_index_resign

  resources :employees, :attendances, :salaries, :withdraws

  root :to => 'home#index'

end

app/models/withdraw.rb
class Withdraw < ActiveRecord::Base
  attr_accessible :date, :amount, :employee, :month_bonus

  belongs_to :employee
end

app/controllers/withdraws_controller.rb
 #encoding: UTF-8

class WithdrawsController < ApplicationController

  def index
    search_by_year(Time.now.year.to_s)
  end

  def search
    search_by_year(params[:year])
    render "index"
  end

  def new
    @employees = Employee.active
    now = Time.now
    @year = now.year
    @month = now.mon - 1
    a = Attendance.order("date DESC").first
    b = Bonus.order("date DESC").first
    date = a.nil? ? nil : a.date
    bonus = b.nil? ? 0 : b.month
    work_day = WorkDay.where("date = ?", date).first
    days = work_day.nil? ? 0 : work_day.total

    attendances = {}
    Attendance.find_all_by_date(date).each do |e|
      attendances[e.employee_id] = e.work_time
    end

    @bonus = {}
    @employees.each do |e| 
      @bonus[e.id] = attendances[e.id] < days ? 0 : bonus
    end
  end

  def create
    @date = Time.local(params[:year], params[:month])
    @withdraws = params[:withdraws]
    @withdraws.each do |it|
      @employee = Employee.find(it[:employee_id])
      Withdraw.create(date: @date, amount: it[:amount], month_bonus: it[:bonus], employee: @employee)
    end
    redirect_to(withdraws_url, :notice => "#{params[:year]}年#{params[:month]}月费用支取信息创建成功.")
  end

  def edit
    @year = params[:year]
    @month = params[:month]   
    @date = Time.local(params[:year], params[:month])
    @withdraws = Withdraw.find_all_by_date(@date)
    if @withdraws.size > 0
      @employees = Employee.all
      @employee_withdraws = Hash.new
      @withdraws.each do |it|
        employee_id = it.employee.id
        @employee_withdraws[employee_id] = it
      end
    else
      redirect_to(withdraws_url, :notice => "#{@year}年#{@month}月费用支取信息未创建.")
    end
  end

  def update
    @date = Time.local(params[:year], params[:month])
    @withdraws = Withdraw.find_all_by_date(@date)
    @withdraws_param = params[:withdraws]
    @withdraws_param.each do |it|
      id = it[:id]
      amount = it[:amount]
      if id.empty?
        @employee = Employee.find(it[:employee_id])
        Withdraw.create(date: @date, amount: amount, month_bonus: it[:bonus], employee: @employee)
      else
        index = @withdraws.index {|o| o.id == id.to_i }
        withdraw = @withdraws[index]
        if withdraw.amount.to_s != amount || withdraw.month_bonus.to_s != it[:bonus]
          withdraw.update_attributes(amount: amount, month_bonus: it[:bonus])
        end
      end
    end
    redirect_to(withdraws_url, :notice => "#{params[:year]}年#{params[:month]}月费用支取信息更新成功.")
  end

private
  def set_nav
    @nav_withdraw = "active"
  end

  def search_by_year(year)
    @year = year
    @months = [1,2,3,4,5,6,7,8,9,10,11,12]
    if !@year.nil? && !@year.empty?
      start_time = Time.local(@year.to_i)
      end_time = Time.local(start_time.year+1)
      @withdraws = Withdraw.where(date: start_time.midnight..end_time.midnight)
      @employees = []
      if @withdraws.size > 0
        @employees = Employee.all
        @employee_withdraws = Hash.new
        @months = []
      end
      @withdraws.each do |it|
        employee_id = it.employee.id
        if @employee_withdraws[employee_id].nil?
          @employee_withdraws[employee_id] = Array.new(12)
        end
        date = it.date
        month = it.date.mon
        @employee_withdraws[employee_id][month-1] = it.amount + it.month_bonus
        @months << month if !@months.include?(month)
      end
      @months.sort!
    end    
    
  end
end

app/views/withdraws/_form.html.erb
<%= form_tag(withdraws_path) %>
	<div class="field">
    <%= label_tag("year", "年份: ") %>
    <%= text_field_tag('year', @year) %>
    <%= label_tag("year", "月份: ") %>
    <%= text_field_tag('month', @month) %>
  </div>
	<table class="table table-striped">
	  <tr>
	    <th>工号</th>
	    <th>姓名</th>
			<th>支取金额</th>
			<th>满勤奖</th>
	  </tr>
	 
		<% @employees.each do |e| %>
	  <tr>
			
	    <td><%= e.id_card %></td>
	    <td><%= e.name %></td>
			<td>
				<%= hidden_field_tag('withdraws[][employee_id]', e.id) %>
				<%= text_field_tag('withdraws[][amount]') %>
			</td>
			<td><%= text_field_tag('withdraws[][bonus]', @bonus[e.id]) %></td>
	  </tr>
		<% end %>
	</table>
  <div class="actions">
    <%= submit_tag "保 存" %>
  </div>
<% $end %>
<br/>

app/views/withdraws/edit.html.erb
<h3>编辑费用支取信息</h3>
 
<%= form_tag(withdraws_update_path) %>
  <div class="field">
    <%= @year %>年<%= @month %>月份员工费用支取列表
    <%= hidden_field_tag('year', @year) %>
    <%= hidden_field_tag('month', @month) %>
  </div>
  <table class="table table-striped">
    <tr>
      <th>工号</th>
      <th>姓名</th>
      <th>支取金额</th>
      <th>满勤奖</th>
    </tr>
   
    <% @employees.each do |employee| %>
      <% withdraw = @employee_withdraws[employee.id] %>
      <% if !withdraw.nil? %>
      <tr class="<%= 'resign' if employee.resigned? %>">
        <td><%= employee.id_card %></td>
        <td><%= employee.name %></td>
        <td>
          <%= hidden_field_tag('withdraws[][id]', withdraw.id) %>
          <%= hidden_field_tag('withdraws[][employee_id]', employee.id) %>
          <%= text_field_tag('withdraws[][amount]', withdraw.amount) %>
        </td>
        <td><%= text_field_tag('withdraws[][bonus]', withdraw.month_bonus) %></td>
      </tr>
      <% end %>
    <% end %>
  </table>
  <div class="actions">
    <%= submit_tag "保 存" %>
  </div>
<% $end %>
<br/>
<%= link_to '返回', withdraws_path %>

app/views/withdraws/index.html.erb
<h3>费用支取列表</h3>

<%= form_tag(withdraws_search_path) %>
	<div class="field">
		<%= label_tag("year", "选择年份") %>
		<%= text_field_tag 'year', @year %>
		<%= submit_tag "查询" %>
	</div>
<% $end %>
<table class="table table-striped">
  <thead>
	<tr>
    <th>工号</th>
    <th>姓名</th>

		<% @months.each do |month| %>
		<th>
			<% if @year.nil? or @year.empty? or @withdraws.size == 0 %>
				<%= month %>月
			<% else %>
				<a href='/withdraws/<%= @year %>/<%= month %>/edit'><%= month %>月</a>
			<% end %>
		</th>
		<% end %>
		<th>合计(￥)</th>
  </tr>
	</thead>

	<% if !@year.nil? and !@year.empty? %>
	<tbody>
	<% total = 0 %>
	<% @employees.each do |employee| %>
	<% array = @employee_withdraws[employee.id] %>
		<% if !array.nil? %>
	  <tr class="<%= 'resign' if employee.resigned? %>">
	    <td><%= employee.id_card %></td>
	    <td><%= employee.name %></td>
			<% sum = 0 %>
			<% @months.each do |month| %>
				<% amount = array[month-1] %>
				<td><%= amount %></td>
				<% sum += amount if !amount.nil?%>
			<% end %>
			<% total += sum %>
	    <td><%= sum %></td>
		</tr>
		<% end %>
	<% end %>
	</tbody>
	<tfoot>
  <tr>
		<td colspan="<%= @months.size+2 %>">总计</td>
		<td><%= total %></td>
	</tr>
	</tfoot>
	<% end %>
</table>
<br />
 
<%= link_to '新建员工支取', new_withdraw_path %>

app/views/withdraws/new.html.erb
<h3>新建费用支取</h3>
 
<%= render 'form' %>
 
<%= link_to '返回', withdraws_path %>