config/routes.rb
Myapp::Application.routes.draw do

  match '/users' => 'home#index'
  match '/users/password' => 'home#index'
  match '/users/password/new' => 'home#index'
  match '/users/sign_up' => 'home#index'
  devise_for :users

  match 'home' => 'home#index'
  match '/attendances/search' => 'attendances#search', :as => :attendances_search
  match '/attendances/:year/:month/edit' => 'attendances#edit'
  match '/attendances/update' => 'attendances#update', :as => :attendances_update
  
  match '/withdraws/search' => 'withdraws#search', :as => :withdraws_search
  match '/withdraws/:year/:month/edit' => 'withdraws#edit'
  match '/withdraws/update' => 'withdraws#update', :as => :withdraws_update

  match '/salaries/search' => 'salaries#search', :as => :salaries_search
  match '/salaries/:year/edit' => 'salaries#edit'
  match '/salaries/update' => 'salaries#update', :as => :salaries_update

  match '/summary' => 'summary#index', :as => :summary
  match '/summary/search' => 'summary#search', :as => :summary_search

  match '/employees/resign/:id' => 'employees#resign', :as => :employee_resign
  match '/employees/entry/:id' => 'employees#entry', :as => :employee_entry
  match '/employees/index_resign' => 'employees#index_resign', :as => :employee_index_resign

  resources :employees, :attendances, :salaries, :withdraws

  root :to => 'home#index'

end

app/models/salary.rb
class Salary < ActiveRecord::Base
  attr_accessible :date, :total, :employee

  belongs_to :employee
end

app/controllers/salaries_controller.rb
 #encoding: UTF-8

class SalariesController < ApplicationController

  def index
    search_by_year(Time.now.year.to_s)
  end

  def search
    search_by_year(params[:year])
    render "index"
  end

  def new
    @employees = Employee.active
    now = Time.now
    @year = now.year
  end

  def create
    @year = params[:year]
    if(!@year.nil? && !@year.empty?)
      @date = Time.local(params[:year])
      count = Salary.where(date: @date).count
      if(count == 0)
        @salaries = params[:salaries]
        @salaries.each do |it|
          @employee = Employee.find(it[:employee_id])
          Salary.create(date: @date, total: it[:total], employee: @employee)
        end
        Bonus.create(date: @date, month: params[:month_bonus], year: params[:year_bonus])
        redirect_to(salaries_url, :notice => "#{params[:year]}年员工薪水信息创建成功.")
      else
        redirect_to(salaries_url, :alert => "创建失败, #{@year}年份的数据已经存在.")
      end
    else
      redirect_to(salaries_url, :alert => "创建失败, 年份格式不正确.")
    end
  end

  def edit
    @year = params[:year]
    @date = Time.local(@year)
    @salaries = Salary.find_all_by_date(@date)
    @bonus = Bonus.find_by_date(@date)
    if @salaries.size > 0
      @employees = Employee.all
      @employee_salaries = Hash.new
      @salaries.each do |it|
        employee_id = it.employee.id
        @employee_salaries[employee_id] = it
      end
    else
      redirect_to(salaries_url, :alert => "#{@year}年员工薪水信息未创建.")
    end
  end

  def update
    @date = Time.local(params[:year])
    @salaries = Salary.find_all_by_date(@date)
    @salaries_param = params[:salaries]
    @salaries_param.each do |it|
      id = it[:id]
      total = it[:total]
      if id.empty?
        @employee = Employee.find(it[:employee_id])
        Salary.create(date: @date, total: total, employee: @employee)
      else
        index = @salaries.index {|o| o.id == id.to_i }
        salary = @salaries[index]
        salary.update_attributes(total: total) if salary.total.to_s != total
      end
    end
    @bonus = Bonus.find_by_date(@date)
    @bonus.update_attributes(month: params[:month_bonus], year: params[:year_bonus])
    redirect_to(salaries_url, :notice => "#{params[:year]}年员工薪水信息更新成功.")
  end

private
  def set_nav
    @nav_salary = "active"
  end

  def search_by_year(year_str)
    @year = year_str
    if @year.nil? || @year.empty?
      @year = Time.now.year.to_s
    end
    @years = @year.split(',')

    years = []
    @years.each do |o|
      years << Time.local(o.to_i)
    end
    @years.sort!

    @total_salaries = {}
    @salaries = Salary.where(date: years)
    @employees = []
    if @salaries.size > 0
      @employees = Employee.all
      @employee_salaries = Hash.new
    end
    @salaries.each do |it|
      employee_id = it.employee.id
      if @employee_salaries[employee_id].nil?
        @employee_salaries[employee_id] = Hash.new
      end
      year = it.date.year.to_s
      @employee_salaries[employee_id][year] = it.total

      if @total_salaries[year].nil?
        @total_salaries[year] = it.total
      else
        @total_salaries[year] += it.total
      end

    end


  end
end

app/views/salaries/_form.html.erb
<%= form_tag(salaries_path) %>
	<div class="field">
    <%= label_tag("year", "年份: ") %>
    <%= text_field_tag('year', @year) %>
    <%= label_tag("month_bonus", "满勤奖: ") %>
    <%= text_field_tag('month_bonus', @month_bonus) %>
    <%= label_tag("year_bonus", "年终奖") %>
    <%= text_field_tag('year_bonus', @year_bonus) %>
  </div>
	<table class="table table-striped">
	  <tr>
	    <th>工号</th>
	    <th>姓名</th>
			<th>工资标准</th>
	  </tr>
	 
		<% @employees.each do |employee| %>
	  <tr>
			
	    <td><%= employee.id_card %></td>
	    <td><%= employee.name %></td>
			<td>
				<%= hidden_field_tag('salaries[][employee_id]', employee.id) %>
				<%= text_field_tag('salaries[][total]') %>
			</td>
	  </tr>
		<% end %>
	</table>
  <div class="actions">
    <%= submit_tag "保 存" %>
  </div>
<% $end %>
<br/>

app/views/salaries/edit.html.erb
<h3>编辑员工工资标准</h3>
 
<%= form_tag(salaries_update_path) %>
  <div class="field">
    <%= @year %>年员工薪水列表
    <%= hidden_field_tag('year', @year) %>
    <%= label_tag("month_bonus", "满勤奖: ") %>
    <%= text_field_tag('month_bonus', @bonus.month) %>
    <%= label_tag("year_bonus", "年终奖") %>
    <%= text_field_tag('year_bonus', @bonus.year) %>
  </div>
  <table class="table table-striped">
    <tr>
      <th>工号</th>
      <th>姓名</th>
      <th>工资标准</th>
    </tr>
   
    <% @employees.each do |employee| %>
    <tr class="<%= 'resign' if employee.resigned? %>">
      <td><%= employee.id_card %></td>
      <td><%= employee.name %></td>
      <td>
        <% salary = @employee_salaries[employee.id] %>
        <% id = salary.id if !salary.nil? %>
        <% total = salary.total if !salary.nil? %>
        <%= hidden_field_tag('salaries[][id]', id) %>
        <%= hidden_field_tag('salaries[][employee_id]', employee.id) %>
        <%= text_field_tag('salaries[][total]', total) %>
      </td>
    </tr>
    <% end %>
  </table>
  <div class="actions">
    <%= submit_tag "保 存" %>
  </div>
<% $end %>
<br/>
<%= link_to '返回', salaries_path %>

app/views/salaries/index.html.erb
<h3>员工薪水列表</h3>

<%= form_tag(salaries_search_path) %>
	<div class="field">
		<%= label_tag("year", "选择年份") %>
		<%= text_field_tag 'year', @year %>
		<%= submit_tag "查询" %>
	</div>
<% $end %>
<table class="table table-striped">
  <thead>
	<tr>
    <th>工号</th>
    <th>姓名</th>
		<% @years.each do |year| %>
		<th>
				<a href='/salaries/<%= year %>/edit'><%= year %>年</a>
		</th>
		<% end %>
  </tr>
	</thead>

	<% if !@year.nil? and !@year.empty? %>
	<tbody>
	<% @employees.each do |employee| %>
  <tr class="<%= 'resign' if employee.resigned? %>">
    <td><%= employee.id_card %></td>
    <td><%= employee.name %></td>
	   <% @years.each do |year| %>
       <% hash = @employee_salaries[employee.id] %>
       <% total = hash[year] if !hash.nil? %>
       <td><%= number_to_currency(total, unit: "￥", precision: 0) %></td>
	   <% end %>
 	</tr>
	<% end %>
	</tbody>
	<tfoot>
  <tr>
		<td colspan="2">总计</td>
		<% @years.each do |year| %>
			<td><%= number_to_currency(@total_salaries[year], unit: "￥", precision: 0) %></td>
		<% end %>
	</tr>
	</tfoot>
	<% end %>
</table>
<br />
 
<%= link_to '新建员工工资标准', new_salary_path %>

app/views/salaries/new.html.erb
<h3>新建员工工资标准</h3>
 
<%= render 'form' %>
 
<%= link_to '返回', salaries_path %>