config/routes.rb
Myapp::Application.routes.draw do

  match '/users' => 'home#index'
  match '/users/password' => 'home#index'
  match '/users/password/new' => 'home#index'
  match '/users/sign_up' => 'home#index'
  devise_for :users

  match 'home' => 'home#index'
  match '/attendances/search' => 'attendances#search', :as => :attendances_search
  match '/attendances/:year/:month/edit' => 'attendances#edit'
  match '/attendances/update' => 'attendances#update', :as => :attendances_update
  
  match '/withdraws/search' => 'withdraws#search', :as => :withdraws_search
  match '/withdraws/:year/:month/edit' => 'withdraws#edit'
  match '/withdraws/update' => 'withdraws#update', :as => :withdraws_update

  match '/salaries/search' => 'salaries#search', :as => :salaries_search
  match '/salaries/:year/edit' => 'salaries#edit'
  match '/salaries/update' => 'salaries#update', :as => :salaries_update

  match '/summary' => 'summary#index', :as => :summary
  match '/summary/search' => 'summary#search', :as => :summary_search

  match '/employees/resign/:id' => 'employees#resign', :as => :employee_resign
  match '/employees/entry/:id' => 'employees#entry', :as => :employee_entry
  match '/employees/index_resign' => 'employees#index_resign', :as => :employee_index_resign

  resources :employees, :attendances, :salaries, :withdraws

  root :to => 'home#index'

end

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-default " role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/home">天翔管理系统</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class='<%=@nav_employee %>'><%= link_to('员工管理', employees_path) %></li>
        <li class='<%=@nav_attendance %>'><%= link_to('考勤管理', attendances_path) %></li>
        <li class='<%=@nav_withdraw %>'><%= link_to('支取管理', withdraws_path) %></li>
        <li class='<%=@nav_salary %>'><%= link_to('薪资管理', salaries_path) %></li>
        <li class='<%=@nav_summary %>'><%= link_to('总账管理', summary_path) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to(current_user.email, '#') %></li>
        <li><%= link_to('注销', destroy_user_session_path, :method => :delete) %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>天翔管理系统</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%= render "layouts/navbar" %>
<% end %>
<% if notice %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-warning"><%= alert %></p>
<% end %>
<div class="container">

  <!-- Main component for a primary marketing message or call to action -->

<%= yield %>
<br/><br/><br/>
</div> <!-- /container -->

  <%= javascript_include_tag "application" %>
  <!-- Latest compiled and minified JavaScript -->
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>  
</body>
</html>